### ISSUE TITLE
SAML2 Service useful or not fields

### ISSUE THREAD

**Issue by Eriikah** [linagora/llng-manager#16]
Please check the useful fields to put in the issuer dashboard, the unchecked ones are going to be shown in the advanced auth param dashboard.

- [X] Entity Identifier
- Security Parameters :
   - [x] Signature
   - [X] Encryption
   - [X] Use certificate in responses
   - [X] Signature method
- NameID formats
   - [ ] Email
   - [ ] X509
   - [ ] Windows
   - [ ] Kerberos
- Authentication contexts
  - [ ] Password
  - [ ] Password protected transport
  - [ ] Kerberos
  - [ ] TLS client
-  Organization
  - [X] Display Name
  - [X] Name
  - [X] URL
- Service Provider
  - [X] Signed Authentication Request
  - [X] Want Assertions Signed
  - [ ] Single Logout (HTTP Redirect, HTTP POST, SOAP)
  - [ ] Assertion Consumer (HTTP Artifact, HTTP POST)
  - [ ] Artifact Resolution
- Identity Provider
  - [X] Want Authentication Request Signed
  - [ ] Single Sign On (HTTP Redirect, HTTP Post, HTTP Artifact)
  - [ ] Single Logout (HTTP Redirect, HTTP Post, HTTP Artifact)
  - [ ] Artifact Resolution
 - [ ] Attribute Authority ( Attribute Service SOAP)
- Advanced 
  - [ ] UTF8 metadata conversion
  - [ ] RelayState session timeout
  - [ ] Use specific query_string method
  - [~] Override Entity ID when acting as IDP
  - [X] SAML sessions module name
  - [X] SAML sessions module options
  - [ ] Common Domain Cookie
  - [ ] Federation (SAML Federation Metadata files)
  - [ ] Discovery Protocol
- [X] download metadata button

**Comment by guimard** [comment]
Please @Buffer0117 @simonelbaz double check my choices

**Comment by simonelbaz** [comment]
The advanced parameters have default values or are empty ?
If they have default values, it would be interesting to display them.

**Comment by guimard** [comment]
> The advanced parameters have default values or are empty ? If they have default values, it would be interesting to display them.

Yes, they have default values, I don't remember to have modified these parameters, neither knowing someone who did it. The idea here is to display only useful parameters in our new dashboards. The actual tree will stay for those who want "very advanced parameters"
